[versions]
activity = "1.13.0"
agp = "9.2.1"
constraintlayout = "2.2.1"
exifinterface = "1.4.2"
fragment = "1.8.9"
glide = "5.0.7"
googleMaterial = "1.13.0"
appcompat = "1.7.1"
material = "1.14.0"
media3 = "1.10.1"
lifecycleViewmodelKtx = "2.11.0"
sentry = "8.48.0"
sentryGradlePlugin = "6.12.0"
commonsImaging = "1.0.0-alpha6"
leakcanary = "2.14"
junit = "4.13.2"
robolectric = "4.16.1"
archCoreTesting = "2.2.0"

[libraries]
activity = { module = "androidx.activity:activity", version.ref = "activity" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
sentry-android = { module = "io.sentry:sentry-android", version.ref = "sentry" }
fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
media3-common = { module = "androidx.media3:media3-common", version.ref = "media3" }
media3-effect = { module = "androidx.media3:media3-effect", version.ref = "media3" }
media3-transformer = { module = "androidx.media3:media3-transformer", version.ref = "media3" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
commons-imaging = { module = "org.apache.commons:commons-imaging", version.ref = "commonsImaging" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
junit = { module = "junit:junit", version.ref = "junit" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "archCoreTesting" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
sentry-android-gradle = { id = "io.sentry.android.gradle", version.ref = "sentryGradlePlugin" }
