name: Sentry Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  create-sentry-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: doubleangels
          SENTRY_PROJECT: redact
        with:
          environment: production
