name: Development Build Testing

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: test-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup Android build
        uses: ./.github/actions/setup-android-build

      - name: Run unit tests
        run: ./gradlew test --no-daemon

      - name: Run Android Lint
        run: ./gradlew lintRelease --no-daemon

      - name: Build Release APK
        run: ./gradlew assembleRelease --no-daemon

  automerge:
    needs: [test]
    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      needs.test.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Enable auto-merge for Dependabot PRs
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ github.token }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge
